version: "3.8"

services:
  traefik:
    image: traefik:v2.5
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --providers.docker=true
      - --providers.docker.network=spark-net
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web-secured.address=:443
      - --certificatesresolvers.mytlschallenge.acme.httpChallenge.entrypoint=web
      - --certificatesresolvers.mytlschallenge.acme.email=admin@chrisich.tech
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "5000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    networks:
      - spark-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.service == traefik
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`traefik.chrisich.tech`)"
        - "traefik.http.routers.api.entrypoints=web-secured"
        - "traefik.http.routers.api.tls=true"
        - "traefik.http.routers.api.tls.certresolver=mytlschallenge"
        - "traefik.http.services.api.loadbalancer.server.port=5000"
        - "traefik.http.routers.api.service=api@internal"

networks:
  spark-net:
    external: true

